GET http://localhost:8080/authorize?user=Mary&password=qwerty
Accept: application/json

###
http://localhost:8080/authorize?user=user&password=
Accept: application/json

###
http://localhost:8080/authorize?user=user&password=pass


